import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kantin FPMIPA",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="w-full h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased
          `}
      >
        {/* w-full h-full overflow-hidden
          bg-[url('/background.jpeg')] bg-cover bg-center bg-no-repeat */}
        {/* Overlay gelap supaya teks kebaca */}
        <div className="w-full h-full bg-black/50">
          {children}
        </div>
      </body>
    </html>
  );
}
